name: CI

on: [push, pull_request]

jobs:
  test_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: cargo test --verbose
    - name: Compute solutions
      run: cargo run
